# <center> Numpy indexing and Selection</center>
<b>Tip : </b> It is almost all like a normal python list

In [1]:
import numpy as np

In [5]:
my_array = np.arange(0, 11)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
print(my_array[1:4])

[1 2 3]


In [9]:
# It will start printing from 2-index
print(my_array[2:])
# It will start printing until 5-index
# NOTE: Last index was exclusive, it will print upto 4th index
print(my_array[:5])

[ 2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]


In [10]:
# Assigning new values
from numpy import arange
assigning_new_values = arange(1, 15)
print(assigning_new_values)
assigning_new_values[0:5] = 0
print(assigning_new_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  0  0  0  0  6  7  8  9 10 11 12 13 14]


In [12]:
array_1 = np.arange(1,10)
print(id(array_1))
array_2 = array_1[1:5]
print(id(array_2))

2691857217936
2691962559248


NOTE: <p style="color:red"> Both array_1 and array_2 values are different but still array_1 values changed whenever array_2 values changed

In [13]:
print(f'array_1: {array_1}')
print(f'array_2: {array_2}')
array_2[:4]=5
print(f'array_1: {array_1}')

array_1: [1 2 3 4 5 6 7 8 9]
array_2: [2 3 4 5]
array_1: [1 5 5 5 5 6 7 8 9]


## Using copy method

In [14]:
my_arr_1 = np.arange(1,15)
my_arr_2 = my_arr_1.copy()
print(f'ID of my_arr_1 : {id(my_arr_1)}')
print(f'ID of my_arr_2 : {id(my_arr_2)}')

ID of my_arr_1 : 2691962557232
ID of my_arr_2 : 2691962558288


In [21]:
print(f'my_arr_1 : {my_arr_1}')
print(f'my_arr_2 : {my_arr_2}')
my_arr_2[:] = 0
print(f'my_arr_1 : {my_arr_1}')
print(f'my_arr_2 : {my_arr_2}')

my_arr_1 : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
my_arr_2 : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
my_arr_1 : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
my_arr_2 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0]


## Accessing an of an array

In [17]:
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
two_dimensional_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
two_dimensional_array[1][1]

5

In [19]:
two_dimensional_array[1,1]

5

In [20]:
# two_dimensional_array[row,column]
two_dimensional_array[:2, 1:]

array([[2, 3],
       [5, 6]])

## Defining boolean array

In [21]:
from numpy.random import randint
random_integers = randint(1, 50, 25)
random_integers

array([42, 19, 37, 31, 16,  7, 13,  7, 29, 26, 19, 13, 33, 20, 30, 28, 32,
       45, 12, 12, 15, 31, 15,  4, 48])

In [22]:
random_integers > 25

array([ True, False,  True,  True, False, False, False, False,  True,
        True, False, False,  True, False,  True,  True,  True,  True,
       False, False, False,  True, False, False,  True])

In [23]:
random_integers[random_integers > 25]

array([42, 37, 31, 29, 26, 33, 30, 28, 32, 45, 31, 48])

## Excercise

In [24]:
my_array = np.arange(50).reshape(5,10)
my_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
my_array[:3, :5][1:, 3:]

array([[13, 14],
       [23, 24]])

In [25]:
my_array[1:3, 3:5]

array([[13, 14],
       [23, 24]])