<center><font size=6 color="#00416d">Numpy Axis</font></center>

In [2]:
import numpy as np

<strong>NUMPY AXES ARE THE DIRECTIONS ALONG THE ROWS AND COLUMNS</strong> <br>
Just like coordinate systems, NumPy arrays also have axes.
<img src="Images\Axis.PNG" alt="Axis" style="width: 600px;"/>


In a 2-dimensional NumPy array, the axes are the directions along the rows and columns

In [3]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## When axis is '0'

When we set axis = 0, the function actually sums down the columns. The result is a new NumPy array that contains the sum of each column.

<img src="Images\axis_0.PNG" alt="axis_0" style="width: 600px;"/>

In [4]:
np.sum(arr, axis=0)

array([12, 15, 18])

### Whe axis is 1

The axis 1 refers to the horizontal direction across the columns

<img src="Images\axis_1.PNG" alt="axis_1" style="width: 600px;"/>

In [6]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

### When Axis is None

In [8]:
np.sum(arr, axis=None)

45

## Example with Concatenation

In [9]:
arr_1 = np.array([[1, 1, 1], [1, 1, 1]])
arr_2 = np.array([[9, 9, 9], [9, 9, 9]])

In [12]:
np.concatenate([arr_1, arr_2])

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [13]:
np.concatenate([arr_1, arr_2], axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [14]:
np.concatenate([arr_1, arr_2], axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

### BE CAREFUL WHEN USING AXES WITH 1-D ARRAYS

In [15]:
arr_1 = np.array([1, 1, 1])
arr_2 = np.array([9, 9, 9])

In [16]:
np.concatenate([arr_1, arr_2], axis=0)

array([1, 1, 1, 9, 9, 9])

In [17]:
np.concatenate([arr_1, arr_2], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

## Good Resources

https://www.sharpsightlabs.com/blog/numpy-axes-explained/