# <center> Numpy </center>

### Importing Numpy Liberary

In [1]:
# It is good to import numpy as np due to many other developers follows the same naming convention
import numpy as np

# Helps to visualize some functions
import pylab as p

### Defining 1-Dimensional array

In [ ]:
my_list = [1, 2, 3]
np.array(my_list)

In [ ]:
# If elements are not same then it will create single dimentional array
# if don't specify dtype it through deprecated warning
j = np.array([[1, 2, 3], [3, 4, 5], [7, 8]], dtype=object)
print(j)
print(j.ndim)

### With list of string

In [ ]:
import string
strings = list(string.ascii_lowercase)
np.array(strings)

### Defining 2-Dimensional array

In [ ]:
two_dimentional_array = [[1, 2, 3], [3, 4, 5], [7, 8, 9]]
np.array(two_dimentional_array)

### To print Dimension

In [ ]:
two_dimensional_array = np.array([[1, 2, 3], [3, 4, 5], [7, 8, 9]])
two_dimensional_array.ndim

### Implementing range function in numpy

In [ ]:
np.arange(0, 10)

In [ ]:
np.arange(0, 10, 2)

### Creating two and three dimensional arrays using arange
<b>Tip</b>: multiplication of number rows and columns equals to number of elements in the array

In [ ]:
# Creating two dimentional array
np.arange(20).reshape(4, 5)

In [ ]:
# Creating three dimentional array
np.arange(27).reshape(3,3,3)

### Define an array with zeros

In [ ]:
np.zeros(3)

<b>NOTE</b>: If you want multiple dimentions you need to pass them in tuple

In [ ]:
np.zeros((2, 4), dtype=int) # Two rows and 4 columns

### Define an array with ones

In [ ]:
np.ones(4)

In [ ]:
# We can add nth dimension by simply adding element in the tuple
np.ones((4,4))

## Full
Return new array of given shape and type, filled with fill_value<br>
<b>Syntax</b>: numpy.full(shape, fill_value, dtype=None, order='C')


In [ ]:
np.full((2, 2), dtype=int, fill_value=10)

### eye matrix

In [ ]:
np.eye(6, 6)

In [ ]:
# k is positive then upper
# by default K=0
# k is negative then lower
np.eye(6, 6, k=-3)

In [ ]:
np.eye(6, 6, k=1)

### Identity Matrix

In [ ]:
np.identity(3) # 3 is for 3X3 matrix

### Diagonal Matrix

In [ ]:
np.diag([1, 2, 3, 4])

## linspace function
The <b>linspace</b> function is used to generate evenly spaced values

In [ ]:
# numpy.linspace(start, stop, num = how_many_number_we_want, endpoint = True, retstep = False, dtype = None)
# np.linspace(from, to, how many values(default is 50), endpoint True means end value included, retstep is the difference)
# it works like a range function
np.linspace(0, 5, 10)

In [ ]:
np.linspace(1,10, num=10, endpoint=False, dtype=int, retstep=True)

In [ ]:
x1 = np.linspace(1, 2, num=10, endpoint=True)
y1 = np.arange(0, 1, 0.1)
for i in zip(x1, y1):
    print(i, end="")

p.xlim(0.9, 1.5)
p.plot(x1, y1, '*')
p.show()

## Creating Identity Matrix / Unit Matrix
A square matrix in which all elements of the principle diagonal are ones and all other elements
are zeros.<br> The number of rows and columns are identical/same in Identity matrix

In [ ]:
np.eye(3)

## Using basic random functions of numpy

### 1 numpy.random.rand(d0, d1, d2, ....,dn)
This function will generate an array of random values in a given shape and poplute it with <br>
random samples from  <span style="background-color: #FFFF00">uniform distribution</span> over [1,0)

In [ ]:
# Generating 1-D array
# Asking 5 random numbers
np.random.rand(10)

In [ ]:
x1 = np.arange(1, 6)
y1 = np.random.rand(5)
print(list(zip(x1, y1)))
p.bar(x1, y1)
p.show()

In [ ]:
# Generating 2-D array
# NOTE : we have not passed the dimention in tuple like we did in other functions
np.random.rand(2,3)

### 2 numpy.random.randn(d0, d1, d2, ....,dn)
Return a sample (or samples) from the “standard normal” distribution.

If positive, int_like or int-convertible arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d<sub>i</sub> are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

This is a convenience function. If you want an interface that takes a tuple as the first argument, use numpy.random.standard_normal instead<br>
<font color="red">TODO : </font>Need to gain knowledge about "standard noraml" and "Gaussian"

In [ ]:
np.random.randn(10)

In [ ]:
np.random.randn(3,3)

In [ ]:
x2 = np.arange(1, 8)
y2 = np.random.randn(7)

p.bar(x2, y2)
p.show()

### 3 numpy.random.randint(low, high=None, size=None, dtype='l')
Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval<br>
[low, high). If high is None (the default), then results are from [0, low).

In [ ]:
np.random.randint(45)

In [ ]:
#Return random integers from low(1) (inclusive) to high(45) (exclusive).
np.random.randint(1, 45)

In [ ]:
# To print 10 ramdon integers
np.random.randint(1, 45, 10)

### Other way of using  random functions

In [ ]:
from numpy.random import randint

In [ ]:
randint(1, 20, 4)

## Frequently used numpy functions

In [ ]:
arr_1 = np.arange(20)
print(arr_1)

In [ ]:
arr_2 = np.random.randint(1,50, 10)
print(arr_2)

### 1 max()
The method helps to find maximum value in the array

In [ ]:
arr_2.max()

### 2 min()
This method helps to find minimum value in the array

In [ ]:
arr_2.min()

### 3 reshape()
The reshape method is used to reshape(to change dimensions) an array

In [ ]:
arr_1.reshape(5,4)

### 4 argmax() and argmin()
To find the index of maximum value and minimum value's index

In [ ]:
maximum_index = arr_1.argmax()
print(maximum_index)
minimum_index = arr_1.argmin()
print(minimum_index)

### 5 shape
The shape function is used to find the shape of an array

In [ ]:
arr_1.shape

In [ ]:
two_dimentional_array = np.array([[1, 2, 3],[4, 5, 6]])
two_dimentional_array.shape

### To check data type

In [ ]:
two_dimentional_array.dtype

### To delete a column  and row in array

In [ ]:
array = np.arange(1, 51).reshape(10, 5)

In [ ]:
array

In [ ]:
# To delete 3rd column
# Syntax: np.delete(array, column_postion, axis=1)
np.delete(array, 2, axis=1)

In [ ]:
# Deleting first row
# Syntax: np.delete(array, row_postion, axis=0)
np.delete(array, 0, axis=0)

### For adding new rows and columns

In [2]:
ele = np.random.randint(1,100, 20).reshape(5, 4)

In [3]:
ele

array([[49, 79, 76, 64],
       [76, 49, 35, 57],
       [32, 34, 47, 77],
       [63, 26, 29, 90],
       [ 9, 48, 74, 29]])

In [11]:
# If you try to insert more elements you will get error like below
# ValueError: could not broadcast input array from shape (1,5) into shape (1,4)
ele_row = [1, 2, 3, 4]
np.insert(ele, 0, ele_row, axis=0)

array([[ 1,  2,  3,  4],
       [49, 79, 76, 64],
       [76, 49, 35, 57],
       [32, 34, 47, 77],
       [63, 26, 29, 90],
       [ 9, 48, 74, 29]])

In [5]:
ele_column = [1, 2, 3, 4, 5]
np.insert(ele, 3, ele_column, axis=1)

array([[49, 79, 76,  1, 64],
       [76, 49, 35,  2, 57],
       [32, 34, 47,  3, 77],
       [63, 26, 29,  4, 90],
       [ 9, 48, 74,  5, 29]])