# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
numbers = np.arange(1,11,dtype=np.int32)
fives = np.full_like(numbers, 5)
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51, dtype='int32')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(25)

#### Create the following matrix:

In [ ]:
a = np.arange(1, 101) * 0.01
a.reshape(10, 10)

In [ ]:
np.linspace(0.01, 1, 100).reshape(10, 10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.linspace(0, 1, 20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[2:, 1:]

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3, 4]

#### WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[:3, 1:2]

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[4:5]

In [ ]:
mat[-1]

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3:]

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)

#### Get the standard deviation of the values in mat
<b>Definations : </b>
<ul>
    <li><b>Mean</b> : Mean is average of a given set of data</li>
  <li><b>Variance</b> : Variance is the sum of squares of differences between all numbers and means.</li>
    <li><b>Standard Deviation</b> :Standard Deviation is square root of variance. It is a measure of the extent to which data varies from the mean.</li>
</ul>
<b>Link</b> : <a href="https://www.geeksforgeeks.org/mathematics-mean-variance-and-standard-deviation/">mean-variance-and-standard-deviation</a>

In [ ]:
np.std(mat)
# (or)
# mat.std()

#### Get the sum of all the columns in mat

In [14]:
row, column = mat.shape
matrix = []
for i in range(column):
    sum = np.sum(mat[:, i])
    matrix.append(sum)
converting_to_array = np.array(matrix)
converting_to_array

NameError: name 'mat' is not defined

In [ ]:
mat.sum(axis=0)

# Great Job!