<center><font size=6 color="#00416d">Usefull Numpy Methods</font></center>

In [2]:
import numpy as np

### numpy.transpose()
Reverse or permute the axes of an array; returns the modified array.

In [4]:
arr = np.array([[1, 2, 3], [3, 5, 6]])
arr

array([[1, 2, 3],
       [3, 5, 6]])

In [5]:
np.transpose(arr)

array([[1, 3],
       [2, 5],
       [3, 6]])

### numpy.array([]).flatten()
Return a copy of the array collapsed into one dimension.

In [9]:
arr = np.array([[1, 2, 3], [3, 5, 6]])
arr

array([[1, 2, 3],
       [3, 5, 6]])

In [10]:
arr.flatten()

array([1, 2, 3, 3, 5, 6])